const CHANGE_WORD_RES = "CHANGE_WORD_RES";
const CHANGE_SEARCHING = "CHANGE_SEARCHING";
const CHANGE_TYPE = "CHANGE_TYPE";
const CHANGE_PAGE = "CHANGE_PAGE";

export { CHANGE_WORD_RES, CHANGE_SEARCHING, CHANGE_TYPE, CHANGE_PAGE };
