const CHANGE_WORD_RES = "CHANGE_WORD_RES";
const CHANGE_SEARCHING = "CHANGE_SEARCHING";
const CHANGE_TYPE = "CHANGE_TYPE";
const CHANGE_PAGE = "CHANGE_PAGE";
const CHANGE_FILTER = "CHANGE_FILTER";
const CHANGE_TERM_FILTER = "CHANGE_TERM_FILTER";
const CHANGE_ENTITIES = "CHANGE_ENTITIES";
const CHANGE_RAFF_TERM = "CHANGE_RAFF_TERM";
const CHANGE_SEARCH_TERM = "CHANGE_SEARCH_TERM";
const CHANGE_INIT = "CHANGE_INIT";

export {
    CHANGE_WORD_RES,
    CHANGE_SEARCHING,
    CHANGE_TYPE,
    CHANGE_PAGE,
    CHANGE_FILTER,
    CHANGE_TERM_FILTER,
    CHANGE_ENTITIES,
    CHANGE_RAFF_TERM,
    CHANGE_SEARCH_TERM,
    CHANGE_INIT,
};
